/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "tinyblckc0000al",
  "description": "前端学习记录",
  "base": "vueBlog",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/c411353d04169c43971032301c836a60.jpg",
        "heroText": "小黑煤",
        "tagline": "先开始，再打磨",
        "actionText": "Get Started >",
        "actionLink": "/node/",
        "features": [
          {
            "title": "记录",
            "details": "好记性不如烂笔头"
          },
          {
            "title": "归纳",
            "details": "学会复盘，学会总结"
          },
          {
            "title": "感悟",
            "details": "一分耕耘，一分收获"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-6ca14f7a",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "Hello,2022",
          "slug": "hello-2022"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": "auto",
    "logo": "/assets/7bb94737ccf45e840c5d4df985ee4e45.jpg",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "前端学习",
        "items": [
          {
            "text": "前端项目",
            "link": "/frontend/project/"
          },
          {
            "text": "前端基础",
            "link": "frontend/essential/"
          }
        ]
      },
      {
        "text": "随感随悟",
        "link": "/memos/"
      },
      {
        "text": "面经",
        "link": "/interview/"
      },
      {
        "text": "问题汇总",
        "link": "/problems/"
      },
      {
        "text": "node.js",
        "link": "/node/"
      },
      {
        "text": "收藏",
        "items": [
          {
            "text": "github",
            "link": "/stars/github/"
          },
          {
            "text": "博客",
            "link": "/stars/blogs/"
          },
          {
            "text": "视频",
            "link": "/stars/videos/"
          },
          {
            "text": "书籍",
            "link": "/stars/books/"
          }
        ]
      }
    ]
  }
}